baseURL = "https://blixenkrone.org/"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true

theme = "hugo-coder"
title = "Simon Blixenkrone"

defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true

disqusShortname = "blix"

[params]
    author = "Simon Blixenkrone"
    info = "Fullstack developer tinkering with high performant applications"
    colorscheme = "light"
    description = "My and myself"
    keywords = "portfolio,developer,personal"
    avatarurl = "assets/mig.png"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "sblixenkrone@gmail.com // @blixenkrone"
    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["./css/extra-style.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/blixenkrone/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/simon-blixenkrone-11b35a107/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/sblixenkrone/"

# Menu links
# [[menu.main]]
#     name = "About"
#     weight = 1
#     url = "/about/"
# [[menu.main]]
#     name = "Projects"
#     weight = 2
#     url = "/projects/"